// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9AwpBPPnu-qKQnir1S2YZhsIy-21U_G0',
    appId: '1:636830472695:web:1d9184d97cd944df0d76f2',
    messagingSenderId: '636830472695',
    projectId: 'ticaret-319dd',
    authDomain: 'ticaret-319dd.firebaseapp.com',
    storageBucket: 'ticaret-319dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyO-uo2CoyUa8E1OfvsxYdRT175mv7xtk',
    appId: '1:636830472695:android:cc9bc8d5d0bece440d76f2',
    messagingSenderId: '636830472695',
    projectId: 'ticaret-319dd',
    storageBucket: 'ticaret-319dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-RX1KvT6ZJlm0uTzWwS5WROvspAW7XgE',
    appId: '1:636830472695:ios:53bbbe6819f29f980d76f2',
    messagingSenderId: '636830472695',
    projectId: 'ticaret-319dd',
    storageBucket: 'ticaret-319dd.appspot.com',
    iosClientId: '636830472695-3ir5rpahkjgmvujq554betng2fmqdh7n.apps.googleusercontent.com',
    iosBundleId: 'com.ticaret.ticaret',
  );
}
